### ISSUE TITLE
Get rid of hardcoded block list

### ISSUE THREAD

**Issue by vswarte** [vswarte/gostatus#21]
[Currently,](https://github.com/vswarte/gostatus/blob/master/modules/bar/bar.go#L41) we're using a `switch` to determine the right block for each config item, we should build something dynamic or generate this list during compilation using `go:generate`

**Comment by vswarte** [comment]
Ideas @AuditeMarlow ?

**Comment by AuditeMarlow** [comment]
Agree, we should take a similar approach for [base/block.go](https://github.com/vswarte/gostatus/blob/master/modules/base/block.go#L34).

**Comment by vswarte** [comment]
@AuditeMarlow There seem to be way to generate an index of all structs within a package. We should probably stick to having all modules register their own blocks.

**Comment by vswarte** [comment]
Thus it would make sense to have the `github.com/vswarte/gostatus/modules/bar` package export a function that registers it to some global block definition list and load from that instead.

**Comment by vswarte** [comment]
Tracking status here #24
