### ISSUE TITLE
Bar shows characters behind tray icons

### ISSUE THREAD

**Issue by AuditeMarlow** [vswarte/gostatus#8]
[As displayed obnoxiously large here.](http://imgur.com/a/6LJ21)

**Comment by vswarte** [comment]
Would love to see a pull-request :-)

**Comment by AuditeMarlow** [comment]
Odd, I'll see if I can reproduce this anywhere else.

**Comment by AuditeMarlow** [comment]
Apparently an i3bar problem, closing.
